[package]
name = "multipart-async"

version = "0.1.0"

authors = ["Austin Bonander <austin.bonander@gmail.com>"]

description = "A backend-agnostic extension for asynchronous HTTP libraries that provides support for POST multipart/form-data requests on for both client and server."

keywords = ["form-data", "hyper", "async", "http", "upload"]

repository = "http://github.com/cybergeek94/multipart-async"

documentation = "http://cybergeek94.github.io/multipart-async/doc/multipart-async/index.html"

license = "MIT OR Apache-2.0"

[dependencies]
env_logger = "0.3"
log = "0.3"
mime = "0.2"
mime_guess = "1.8"
rand = "0.3"
tempdir = "0.3"

[dependencies.buf_redux]
path = "../buf_redux"

[dependencies.hyper]
optional = true
git = "https://github.com/hyperium/hyper"

[dependencies.memchr]
optional = true
version = "0.1"

[features]
client = []
default = ["hyper", "server", "client"]
server = ["memchr"]

[dev_dependencies]
hyper = { git = "https://github.com/hyperium/hyper" }
