[package]
name = "multipart-async"

version = "0.0.1"

authors = ["Austin Bonander <austin.bonander@gmail.com>"]

description = "A backend-agnostic extension for asynchronous HTTP libraries that provides support for POST multipart/form-data requests on for both client and server."

keywords = ["form-data", "hyper", "async", "http", "upload"]

repository = "http://github.com/cybergeek94/multipart-async"

documentation = "http://cybergeek94.github.io/multipart-async/doc/multipart-async/index.html"

license = "MIT OR Apache-2.0"

[dependencies]
display_bytes = "0.1"
env_logger = "0.3"
futures = "0.1"
log = "0.3"
mime = "0.3"
mime_guess = "2.0.0-alpha.1"
rand = "0.3"
tempdir = "0.3"

hyper = { version = "0.11", optional = true }
httparse = { version = "1.0", optional = true }
twoway = { version = "0.1", optional = true }

[features]
client = []
default = ["hyper", "server", "client"]
server = ["twoway", "httparse"]
sse4 = ["twoway/pcmp"]
# Use `Arc` instead of `Rc` where needed
use_arc = []
